name = "EntityTools"
uuid = "b454753b-5441-4cda-8f2f-910cbcbb7d97"
authors = ["Ludwig BÃ¶ss <ludwig.boess@outlook.de> and contributors"]
version = "0.1.0"

[deps]
ADIOS2 = "e0ce9d3b-0dbd-416f-8264-ccca772f60ec"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ADIOS2 = ">=1.4"
CairoMakie = ">=0.13"
DelimitedFiles = "1"
Distributions = ">=0.25"
FFTW = "1.9.0"
Printf = "1"
ProgressMeter = "1"
StatsBase = ">=0.34"
Unitful = "1"
julia = ">=1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
